Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -36,6 +36,17 @@ jobs:
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+    - name: Test with pytest
+      run: |
+         python -m pytest --verbose --junit-xml=junit.xml
+    - name: Publish test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() ||failure() #always run even if the previous setp fails
+      with:
+        report_path: '**junit.xml'
+        detailed_sumary: true
+        include_passed: true
+      
     - name: Run pytest (skip if no tests)
       run: |
        if find . -name "test_*.py" | grep -q .; then
